[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x7e8294"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[colors.normal]
black = "0x363a4e"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[colors.primary]
background = "0x2b2d3a"
foreground = "0xc5cdd9"

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[colors.edge_dark_neon.bright]
#black = "0x7e8294"
#blue = "0x6cb6eb"
#cyan = "0x5dbbc1"
#green = "0xa0c980"
#magenta = "0xd38aea"
#red = "0xec7279"
#white = "0xc5cdd9"
#yellow = "0xdeb974"

#[colors.edge_dark_neon.normal]
#black = "0x363a4e"
#blue = "0x6cb6eb"
#cyan = "0x5dbbc1"
#green = "0xa0c980"
#magenta = "0xd38aea"
#red = "0xec7279"
#white = "0xc5cdd9"
#yellow = "0xdeb974"

#[colors.edge_dark_neon.primary]
#foreground = "0xc5cdd9"
#background = "0x2b2d3a"

[shell]
args = ["--login"]
program = "/bin/zsh"
