---

- name: Update apt
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade apt
  become: true
  apt: upgrade=yes

- name: Install apt packages
  become: true
  apt:
    pkg: "{{ packages }}"
