---

packages:
  # Env
  - i3
  - py3status
  # Utils
  - zsh
  - fzf
  - git
  - git-gui
  - meld
  - fonts-symbola  # to fix gitk
  - vim
  - curl
  - wget
  - htop
  - fzf
  - jq
  - ripgrep
  - yamllint
  - xdotool
  # Dev
  - build-essential
  - gcc
  - g++
  - clangd
  - bear
  - python3
  - python3-pip
  - python3-virtualenv
  - python3-virtualenvwrapper
  - sqlite3
  - libsqlite3-dev
  - cmake
  - clang
  - automake
  - autotools
  - libtool
