---

# https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly

- name: Get rust-analyzer
  become: true
  get_url:
    url: https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer-x86_64-unknown-linux-gnu.gz
    dest: /usr/local/bin/rust-analyzer-tmp.gz

- name: Install rust-analyzer
  become: true
  shell: |
    gzip -d rust-analyzer-tmp.gz
    mv rust-analyzer-tmp rust-analyzer
    chmod +x rust-analyzer
  args:
    chdir: /usr/local/bin/
  changed_when: false

# TODO: changed_when checksum changes would be cleaner
