---

- name: Create temporary directory
  tempfile:
    state: directory
    suffix: tmp
  register: temp_dir
  changed_when: false

# TODO: Check checksum is different
- name: Get ninja
  get_url:
    url: https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
    dest: "{{ temp_dir.path }}/ninja.zip"
  changed_when: false

- name: Extract zip
  unarchive:
    src: "{{ temp_dir.path }}/ninja.zip"
    dest: "{{ temp_dir.path }}"
  changed_when: false

- name: Install ninja
  become: true
  shell: |
    chmod +x {{ temp_dir.path }}/ninja
    mv {{ temp_dir.path }}/ninja /usr/local/bin/

- name: Remove old lua-language-server
  become: true
  file:
    state: absent
    path: /opt/lua-language-server

- name: Clone lua-language-server
  become: true
  git:
    repo: https://github.com/sumneko/lua-language-server
    track_submodules: true
    version: master
    depth: 1
    dest: /opt/lua-language-server

- name: Build lua-language-server
  become: true
  shell: |
    cd 3rd/luamake
    compile/install.sh
    cd ../..
    ./3rd/luamake/luamake rebuild
  args:
    chdir: /opt/lua-language-server
