---

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    version: master
    depth: 1
    dest: "{{ localuser_dir }}/.fzf/"

- name: Install fzf
  command: "{{ localuser_dir }}/.fzf/install --all"
  register: fzf_result
  changed_when: '"Already exists" not in fzf_result.stdout'
