---

- name: Install obsidian note taking application
  become: true
  shell: |
    #!/usr/bin/env bash
    set -e

    icon_url="https://cdn.discordapp.com/icons/686053708261228577/1361e62fed2fee55c7885103c864e2a8.png"
    dl_url=$( curl -s https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest  \
    | grep "browser_download_url.*AppImage" | tail -n 1 | cut -d '"' -f 4 )

    curl --location --output /tmp/Obsidian.AppImage "$dl_url"
    curl --location --output /tmp/obsidian.png "$icon_url"

    mkdir --parents /opt/obsidian/
    mv /tmp/Obsidian.AppImage /opt/obsidian
    chmod +x /opt/obsidian/Obsidian.AppImage
    mv /tmp/obsidian.png /opt/obsidian
    ln -sf /opt/obsidian/obsidian.png /usr/share/pixmaps

    echo "[Desktop Entry]
    Type=Application
    Name=Obsidian
    Exec=/opt/obsidian/Obsidian.AppImage
    Icon=obsidian
    Terminal=false" > {{ localuser_dir }}/.local/share/applications/obsidian.desktop

    update-desktop-database {{ localuser_dir }}/.local/share/applications
    echo "install ok"
