---

- name: Install dependencies
  become: true
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3

- name: Install alacritty
  command: "{{ localuser_dir }}/.cargo/bin/cargo install alacritty"
  register: alacritty
  changed_when: '"release [optimized]" in alacritty.stdout'
